# The name of your Worker. Alphanumeric values and dashes only.
name = "comment-worker"

# The entrypoint/path to the file that will be executed.
main = "./src/index.js"

# Whether you use `<NAME>.<SUBDOMAIN>.workers.dev` to
# test and deploy your Worker.
# @default `true`
workers_dev = true

# A date in the form yyyy-mm-dd, which will be used to determine
# which version of the Workers runtime is used.
compatibility_date = "2023-08-11"

## example config ##
#routes = [
#    { pattern = "comments.zanechua.com", custom_domain = true }
#]
#
[vars]
GITHUB_ORGANIZATION_SLUG = "4gYAagbj"
GITHUB_REPOSITORY_SLUG = "comment-worker"
GITHUB_REPOSITORY_BRANCH = "main"
CW_ALLOWED_ORIGINS = "https://svansr.github.io"
GITHUB_APP_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCob7ylFRWtIsfz\nhp4R3vJfR1eXpXQE21XtaIRN1vL715mauV9PSa90Y5xCKIjTRv8a4h4mQj6JLEOC\nfwxBqr/vHoDXqscwJeS6DlAn1z59YHawllhf6OuG845jBm9aBAmK50fS9SUB8Cpg\nKoB34Ob0Cbjo7GtaWv9Vu5wFKFtzmwFZRpFNq/695VuKO04KKoUTMHr5azysR+FW\nz5i4JKAAaUNsoBSmFNXHqd/qLtfxiTAPnJuI/iFXz70hVqHkb++lDoujE0e/lZKj\ngNgKoYvNA7QIePXRfpk8BXmAlh3Iy0MB0I8Cx3CVd9uNvMbl7nDxJMfHpEjM93WG\nyZaLOnQtAgMBAAECggEAAbbZaai0RsXS2SSmmTH2r4ePWajCbIY68qacqhok8PE5\ny/xU/v6V/Y5B+d5lvhi74e8pNWR5NHYx3bMjUcvGFk3uK8O+MTxBfq9Em5MyPJ5t\nttBg5+D7/Kyf51waaAUgf7xo27nI/aMPG1lzY0TztMogiqZVVV8VuC6noNnPTHbk\nK1zl0ydtMobSPQct5tzP+t3Upnxdo+ixcW1FJvynntQzKYk9HUrR9AOUO77uZPoD\nkko1GWHWvjMZz8HiJrPRkTAZSPnlQxJGn0e9ODci2w1uCjJyYk3HcQt2Opnuah6f\nU2xkn05ciOhYxBusE5HJq/iOYlahiiCJQMGZWiR09QKBgQDTngkL9lYamb83BUaG\n9Yl8NYNMfQOcCu9v7llol9DOHcz9svW65dPPZXnNRi7JKi9YAmWCEk/LKPZA3QJ7\nimxDlAQ/UI1WCoIUSlPtqJoblNImtQ4ctSD4JlX6WYCJsRwMzyTH88s/KrKdGo1Z\nDGXLhvPgtwT9/la+gvZ5NCEdDwKBgQDLw0ZGwrSOkek1FLlQd8LexS96W8ZhMkwG\nqdGyI3jQ7pPU/K2OIP+u8GBWczGD4CRIxkutAOAvBRMNZprOPBbCUy72UhHxVhGx\nLm8fXauuUvNW9+JfihKAJRMuh1vPLe5eeu9PbQY7rTb59SDGCGkUz9AL83Ju+lpV\nCBp2GWETAwKBgQCv1XWg6et7qNqYZhrHEwhNG83gZVP1eaSgNcU2wkaurVZiSywh\nQsxvXNsLNNC1OAckssEThhGlNoD/PmTMsCTrNfcdgNofbxXMtEHujJSYbFz96p0y\nP1KIvpncLjg+sNokzo26UxlDgD/viFuAbWu75IOJ6akNPyNmoz0XUrhdAwKBgGDh\nX7CVMrP2vCL4z4Nq7cRtjL1olVHxUCR66bEBHJh6Vt+VpA9HsUnEEIoKCyjgkV/o\nqGKBYBX7G6vrdP9JoqiSVGnZa56Lha3wnfUT3GTuG7Tl90PlqhYzioM86HIBLKzP\nVqk09Rm6qcD+w65koVG73PdRsL8DWZ/EUpCEUJtxAoGBAIEqZZc5iiXLIFbcTn7I\n9m186Kz4YGh9WMTSMPyc6Er+HhBAoXdXwL920acBqbR16VajCa2Db2ItDjehP0TM\nsXBMMtJ3cY+i1BS/FdtTrOoCrFxnho1JTI1Jr/bt2334ZTM56y1UaC8RGnxHsnRW\neJZMKQVvAPlOoRvL1LAXCfRX\n-----END PRIVATE KEY-----"
CW_DEBUG = true
GITHUB_APP_ID = 111293932